// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("FileStorage")]
[assembly: AssemblyDescriptionAttribute("FileStorage")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("FileStorage")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0+13.Branch.master.Sha.ff7fc0505c6de4db204505d4435762e92d21c933")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
    }
}
